### ISSUE TITLE
Display Issue #2 (The Good Move 0.6)

### ISSUE THREAD

**Issue by cherylz** [wikimigrate/wikimigrate#28]
iPhone 6 + Chrome
Could be better if Filters won't cover all the option cards? Maybe reveal at least a half of one card?
![wechatimg60](https://cloud.githubusercontent.com/assets/9253596/25305316/a066e5d4-27ab-11e7-93f8-908857d6e19f.jpeg)

**Comment by andyshuhsin** [comment]
Implemented
